# Organisations

Organizations:

	- &OrdererOrg
		Name: OrdererOrg
		ID: OrdererMSP
		MSPDir: crypto-config/ordererOrganizations/my-network.com/msp

	- &MagnetoCorp
		Name: MagnetoCorpMSP
		ID: MagnetoCorpMSP
		MSPDir: crypto-config/peerOrganizations/magnetocorp.my-network.com/msp
		AnchorPeers:
			- Host: peer0.magnetocorp.my-network.com
				Port: 7051

	- &DigiBank
		Name: DigiBankMSP
		ID: DigiBankMSP
		MSPDir: crypto-config/peerOrganizations/digibank.my-network.com/msp
		AnchorPeers:
			- Host: peer0.digibank.my-network.com
				Port: 8051

# Application

Application: &ApplicationDefaults

	Organizations:

# Orderer

Orderer: &OrdererDefaults

	OrdererType: solo
	Addresses:
		- orderer.my-network.com:7050
	BatchTimeout: 2s
	BatchSize:
		MaxMessageCount: 10
		AbsoluteMaxBytes: 99 MB
		PreferredMaxBytes: 512 KB
	Kafka:
		Brokers:
			- 127.0.0.1:9092

	Organizations:

# Profiles

Profiles:
		OrdererGenesis:
			Orderer:
				<<: *OrdererDefaults
				Organizations:
					- *OrdererOrg
			Consortiums:
				MyConsortium:
					Organizations:
						- *MagnetoCorp
						- *DigiBank

		MyChannel:
			Consortium: MyConsortium
			Application:
				<<: *ApplicationDefaults
				Organizations:
						- *MagnetoCorp
						- *DigiBank
